### ISSUE TITLE
npm install is required for onchain-utils layer before deploying AWS resources

### ISSUE THREAD

**Issue by tdc-yamada-ya** [aws-samples/nft-access-control-lambda-authorizer#5]
The following error occurred when lambda function is called.

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'ethers'\nRequire stack:\n- /opt/nodejs/node_modules/onchain-utils/providers.js\n- /opt/nodejs/node_modules/onchain-utils/index.js\n- /var/task/deploy_contract.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'ethers'",
        "Require stack:",
        "- /opt/nodejs/node_modules/onchain-utils/providers.js",
        "- /opt/nodejs/node_modules/onchain-utils/index.js",
        "- /var/task/deploy_contract.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/Runtime.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:221:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:279:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:34)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

`ethers` package cannot be resolved in `onchain-utils` layer code.
I think `npm install` step is required in `onchain-utils` layer before deploying.

```bash
cd serverless/lambdas/shared/nodejs
npm install
```

This step is not written in `README.md` file.

**Comment by matan-aws** [comment]
you're correct. the layer definition in the sam template didn't include the build method part. I've updated the repo to reflect the change (no need to change the readme)
